---

- name: save host
  uri:
    url: "{{ awx_host }}/api/v2/inventories/{{ awx_inventory_id }}/hosts/"
    user: "{{ awx_admin_user }}"
    password: "{{ awx_admin_password }}"
    method: POST
    validate_certs: false
    return_content: yes
    force_basic_auth: yes
    status_code: 201
    headers:
      Accept: "application/json"
    body_format: json
    body: "{\"inventory\": {{ awx_inventory_id }},\"name\":\"{{ ip_address }}\", \"variables\": \"ansible_port: {{ awx_host_port }}\\nansible_user: {{ awx_host_username }}\\nansible_become: {{ awx_host_become }}\"}"
  ignore_errors: no 
  when: (ip_address is defined)
  
- name: Set Stats for Workflow
  set_stats:
    data:
      ip_address: "{{ ip_address }}"
  when: (ip_address is defined)